# Generated by Django 5.2.4 on 2025-07-19 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listening', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField(unique=True)),
                ('question_text', models.CharField(blank=True, help_text='For MCQs or Matching items.', max_length=500)),
                ('choices', models.TextField(blank=True, help_text='For Multiple Choice, separate options with a semicolon (;).')),
                ('correct_answer', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['question_number'],
            },
        ),
        migrations.RemoveField(
            model_name='listeningquestion',
            name='block',
        ),
        migrations.RemoveField(
            model_name='listeningtest',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='listeningtest',
            name='transcript',
        ),
        migrations.AlterField(
            model_name='listeningtest',
            name='title',
            field=models.CharField(help_text="e.g., 'IELTS Listening Test 1'", max_length=200),
        ),
        migrations.CreateModel(
            name='ListeningPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.PositiveIntegerField()),
                ('audio_file', models.FileField(upload_to='listening_parts/')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='listening.listeningtest')),
            ],
            options={
                'ordering': ['part_number'],
            },
        ),
        migrations.AlterField(
            model_name='listeninguseranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listening.question'),
        ),
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_range', models.CharField(help_text="e.g., 'Questions 1-10'", max_length=50)),
                ('group_type', models.CharField(choices=[('note_completion', 'Note/Form/Sentence Completion'), ('multiple_choice', 'Multiple Choice'), ('map_labelling', 'Map/Diagram Labelling'), ('matching', 'Matching')], max_length=50)),
                ('instructions', models.TextField()),
                ('image', models.ImageField(blank=True, help_text='Upload a map or diagram if needed.', null=True, upload_to='listening_images/')),
                ('prose_content', models.TextField(blank=True, help_text="For note completion, use {{num}} for blanks. e.g., 'Area: {{1}} hectares'")),
                ('options_list', models.TextField(blank=True, help_text='For matching, list options separated by semicolons (;).')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_groups', to='listening.listeningpart')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='listening.questiongroup'),
        ),
        migrations.DeleteModel(
            name='ListeningQuestionBlock',
        ),
        migrations.DeleteModel(
            name='ListeningQuestion',
        ),
    ]
