# Generated by Django 5.2.4 on 2025-07-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='blocked_until',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
