# Generated by Django 5.2.4 on 2025-07-19 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.TextField(help_text='Instructions for this group of questions.')),
                ('question_type', models.CharField(choices=[('short_answer', 'Short Answer / Completion'), ('multiple_choice', 'Multiple Choice'), ('true_false_not_given', 'True/False/Not Given'), ('matching', 'Matching (e.g., Headings)')], max_length=50)),
                ('options_list', models.TextField(blank=True, help_text='For Matching questions, provide the list of options here, separated by semicolons (;).')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('passage_1', models.TextField()),
                ('passage_2', models.TextField()),
                ('passage_3', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField(unique=True)),
                ('question_text', models.CharField(blank=True, help_text="The question itself, or the item to be matched (e.g., 'Paragraph A').", max_length=500)),
                ('choices', models.TextField(blank=True, help_text='For Multiple Choice questions only, separate choices with a semicolon (;).')),
                ('correct_answer', models.CharField(max_length=200)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='reading.questionblock')),
            ],
            options={
                'ordering': ['question_number'],
            },
        ),
        migrations.AddField(
            model_name='questionblock',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_blocks', to='reading.readingtest'),
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_answer', models.CharField(blank=True, max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reading.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
