# Generated by Django 5.2.4 on 2025-07-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionblock',
            name='prose_content',
            field=models.TextField(blank=True, help_text="For note completion, use {{num}} for blanks. e.g., 'Area: {{1}} hectares'"),
        ),
    ]
