# Generated by Django 5.2.4 on 2025-07-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0003_question_passage_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='passage_number',
        ),
        migrations.AddField(
            model_name='questionblock',
            name='passage_number',
            field=models.IntegerField(choices=[(1, 'Passage 1'), (2, 'Passage 2'), (3, 'Passage 3')], default=1),
        ),
    ]
