# Generated by Django 5.2.4 on 2025-07-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0004_remove_question_passage_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_number',
            field=models.PositiveIntegerField(),
        ),
    ]
